#!/usr/bin/env node
// Conceptify skill — post-process generated SVG (d2 / Graphviz dot) for
// inlining into an artifact. Implements the deterministic recipe in
// references/rendering.md + artifact-spec §4.4:
//
//   d2:  strip XML prolog · delete embedded <style> blocks (fonts + baked
//        theme; the adapter CSS replaces them) · decode each group's
//        base64 object key and stamp `data-cfy-id="<fig>.<derived>"`.
//   dot: strip prolog/DOCTYPE/generator comments · remove generated
//        positional id="graph0|node1|edge1|clust1" attributes · read each
//        <g class="node|edge|cluster"> <title> and stamp the derived id.
//
// Id derivation (artifact-spec §4.4, normative): lowercase → `->`/`→`
// becomes `-to-` → runs outside [a-z0-9] collapse to `-` → trim `-`;
// collisions get `-2`, `-3`, … in document order.
//
// Mermaid SVG is NOT supported: per OQ5 (conceptify-57l.5) Mermaid
// pre-rendering is not in the toolchain — see rendering.md.
//
// Usage:
//   node postprocess-svg.mjs --fig fig-request-flow --input diagram.svg
//   d2 --layout=elk --pad 0 x.d2 - | node postprocess-svg.mjs --fig fig-x
//   node postprocess-svg.mjs --fig fig-x --input diagram.svg --write
//
// Flags:
//   --fig <id>     (required) figure data-cfy-id; element ids are
//                  namespaced under it: <fig>.<derived-segment>
//   --input <file> read from file instead of stdin
//   --tool d2|dot  skip autodetection
//   --write        rewrite --input in place instead of printing to stdout
//
// Output: processed SVG on stdout (or in place with --write); a summary
// of stamped ids on stderr. Deterministic and idempotent: re-running on
// already-processed SVG is a no-op (already-stamped groups are skipped).
// Zero dependencies (node built-ins only).

import fs from "node:fs";
import process from "node:process";

function arg(name) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 ? process.argv[i + 1] : undefined;
}
const has = (name) => process.argv.includes(`--${name}`);

const fig = arg("fig");
const input = arg("input");
const ID_RE = /^[a-z](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z](?:[a-z0-9-]*[a-z0-9])?)*$/;

if (!fig) {
  console.error(
    "usage: postprocess-svg.mjs --fig <figure-id> [--input <file>] [--tool d2|dot] [--write]",
  );
  process.exit(2);
}
if (!ID_RE.test(fig)) {
  console.error(`error: --fig "${fig}" violates the id grammar (artifact-spec §4.2)`);
  process.exit(2);
}
if (has("write") && !input) {
  console.error("error: --write requires --input");
  process.exit(2);
}

// (async stdin read: readFileSync(0) EAGAINs on macOS non-blocking pipes)
async function readStdin() {
  const chunks = [];
  for await (const c of process.stdin) chunks.push(c);
  return Buffer.concat(chunks).toString("utf8");
}
let svg = input ? fs.readFileSync(input, "utf8") : await readStdin();

// --- detect tool ----------------------------------------------------------
let tool = arg("tool");
if (!tool) {
  if (/data-d2-version=/.test(svg) || /class="[^"]*\bd2-svg\b/.test(svg)) tool = "d2";
  else if (/Generated by graphviz/i.test(svg) || /<g[^>]*class="graph[" ]/.test(svg)) tool = "dot";
  else if (/aria-roledescription=/.test(svg) || /id="my-svg"/.test(svg)) tool = "mermaid";
}
if (tool === "mermaid") {
  console.error(
    "error: Mermaid SVG is not supported — Mermaid pre-rendering is not in the " +
      "toolchain (OQ5, see references/rendering.md). Re-author the diagram in d2 or DOT.",
  );
  process.exit(2);
}
if (tool !== "d2" && tool !== "dot") {
  console.error("error: could not detect d2/dot output; pass --tool d2|dot");
  process.exit(2);
}

// --- shared helpers -------------------------------------------------------

// artifact-spec §4.4 derivation, steps 1–4 (step 5, collisions, is below).
function derive(name) {
  return name
    .toLowerCase()
    .replace(/->|→/g, "-to-")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function decodeEntities(s) {
  return s
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&");
}

// 1. Strip everything before the opening <svg (XML prolog, DOCTYPE,
//    generator comments). No-op when already stripped.
const svgStart = svg.indexOf("<svg");
if (svgStart === -1) {
  console.error("error: input contains no <svg> element");
  process.exit(2);
}
svg = svg.slice(svgStart).trimEnd() + "\n";

// Collect ids already present (pre-stamped runs, other figures) so
// collision suffixes never duplicate them — keeps re-runs idempotent.
const used = new Set();
for (const m of svg.matchAll(/data-cfy-id="([^"]*)"/g)) used.add(m[1]);

const stamped = [];
const warnings = [];
let skippedAlready = 0;

function claim(segment) {
  if (!segment) return null;
  let id = `${fig}.${segment}`;
  for (let n = 2; used.has(id); n++) id = `${fig}.${segment}-${n}`;
  used.add(id);
  if (id.length > 64) warnings.push(`id exceeds 64 chars (W-ID-FORMAT): ${id} — shorten the DSL key`);
  if (!ID_RE.test(id)) warnings.push(`derived id violates the grammar (W-ID-FORMAT): ${id}`);
  return id;
}

// --- d2 -------------------------------------------------------------------
if (tool === "d2") {
  // 2. Delete the embedded <style> blocks (base64 @font-face data + baked
  //    light-only theme). The adapter CSS in rendering.md replaces them.
  svg = svg.replace(/<style[^>]*>[\s\S]*?<\/style>/g, "");

  // 3. Stamp groups whose class is the base64-encoded, HTML-escaped d2
  //    object key (shapes, containers, connections).
  const b64key = (cls) => {
    if (!/^[A-Za-z0-9+/]+={0,2}$/.test(cls) || cls.length % 4 !== 0) return null;
    const decoded = Buffer.from(cls, "base64").toString("utf8");
    // strict round-trip: rejects class names that merely look like base64
    if (Buffer.from(decoded, "utf8").toString("base64") !== cls) return null;
    return decodeEntities(decoded);
  };

  svg = svg.replace(/<g\b([^>]*)>/g, (tag, attrs) => {
    if (attrs.includes("data-cfy-id=")) {
      skippedAlready++;
      return tag;
    }
    const cls = /(?:^|\s)class="([^"\s]+)"/.exec(attrs);
    if (!cls) return tag;
    const key = b64key(cls[1]);
    if (key === null) return tag;
    // connection keys look like `(client -> middleware)[n]` — optionally
    // container-prefixed for edges inside a container:
    // `walk.(ignore -> globset)[n]`. n=0 is the first (often only)
    // parallel edge and gets no suffix, n>=1 gets -{n+1}.
    let segment;
    const conn = /^(?:(.*)\.)?\((.*)\)\[(\d+)\]$/.exec(key);
    if (conn) {
      // Sequence-diagram lifelines are edges with an empty destination:
      // `(walker -- )[0]`. A lifeline is not a commentable concept (and
      // would otherwise stamp as `<actor>-2`, a diagram-tall ambiguous
      // click target) — skip it.
      if (/(?:^|\s)--\s*$/.test(conn[2])) return tag;
      segment = derive(conn[1] ? `${conn[1]} ${conn[2]}` : conn[2]);
      if (segment && Number(conn[3]) >= 1) segment += `-${Number(conn[3]) + 1}`;
    } else {
      segment = derive(key);
    }
    const id = claim(segment);
    if (!id) {
      warnings.push(`d2 key "${key}" derives to an empty id — not stamped`);
      return tag;
    }
    stamped.push(id);
    return `<g data-cfy-id="${id}"${attrs}>`;
  });
}

// --- dot ------------------------------------------------------------------
if (tool === "dot") {
  // 2. Remove generated positional id attributes (graph0, node1, edge1,
  //    clust1, …) — they collide across multiple DOT diagrams.
  svg = svg.replace(/\s+id="(?:graph|node|edge|clust)\d+"/g, "");

  // 3. Stamp <g class="node|edge|cluster"> via the child <title> that
  //    holds the DOT name (`a`, `a->b`, `cluster_x`). Root graph <g> is
  //    skipped — the <figure> wrapper carries the figure id.
  svg = svg.replace(
    /<g\b([^>]*)>(\s*<title>([^<]*)<\/title>)/g,
    (whole, attrs, titlePart, title) => {
      if (attrs.includes("data-cfy-id=")) {
        skippedAlready++;
        return whole;
      }
      const cls = /(?:^|\s)class="([^"]*)"/.exec(attrs);
      if (!cls || !/\b(node|edge|cluster)\b/.test(cls[1])) return whole;
      const id = claim(derive(decodeEntities(title)));
      if (!id) {
        warnings.push(`DOT name "${title}" derives to an empty id — not stamped`);
        return whole;
      }
      stamped.push(id);
      return `<g data-cfy-id="${id}"${attrs}>${titlePart}`;
    },
  );
}

// --- output + summary -----------------------------------------------------
if (has("write")) fs.writeFileSync(input, svg);
else process.stdout.write(svg);

console.error(`postprocess-svg: tool=${tool} fig=${fig}`);
console.error(
  `  stamped ${stamped.length} id(s)` +
    (skippedAlready ? ` (${skippedAlready} already stamped, left as-is)` : ""),
);
for (const id of stamped) console.error(`    ${id}`);
for (const w of warnings) console.error(`  warning: ${w}`);
if (stamped.length + skippedAlready < 3) {
  console.error(
    "  note: fewer than 3 anchor bearers — the save-artifact validator warns " +
      "(W-ANCHOR-DIAGRAM) on SVGs with >= 6 shapes",
  );
}
console.error(
  `  next: wrap in <figure class="cfy-diagram" data-cfy-id="${fig}"> + <figcaption>,` +
    " preceded by the <!--cfy:src--> comment (rendering.md)",
);
